# makefile for the main, to run the included test program,
# replace main.c with test.c or run the line at the top of test.c

mymemory: main.c memory.c datatype.c bst.c list.c

	gcc -o mymemory main.c memory.c datatype.c bst.c list.c	

clean:

	rm -f mymemory
